### ISSUE TITLE
Allow only defined users to be connected

### ISSUE THREAD

**Issue by xbeta** [debops/ansible-sshd#18]
Doc: http://www.tldp.org/LDP/solrhe/Securing-Optimizing-Linux-RH-Edition-v1.3/chap15sec122.html

`AllowUsers myuser`

**Comment by drybjed** [comment]
This HOWTO you linked seems to be from 2000, at least from what copyright notice tells...
```
Madhu "Maddy"
Copyright © 2000 by Gerhard Mourani and OpenDocs, LLC.
Copyright © 2000 by Madhusudan (Madhu "Maddy") XML Source
```
Anyway, using `AllowUsers` directly in `/etc/ssh/sshd_config` is terribly inefficient - when a new user comes along that requires `ssh` access, you need to reconfigure `sshd` daemon again, and again.

Better way to handle this is using `AllowGroups`, which is what DebOps sets up. That way, you can just add an user account to specific system group(s) and they will automatically have access to `ssh` without modifying the daemon configuration file.

At the moment in DebOps, groups that grant SSH access are:

- `admins` - system administrator accounts, have complete access to SSH, `sudo` among other things;

- `root` - requires SSH access to perform backups remotely;

- `sshusers` - accounts in this group can connect to the host using SSH, but don't gain any additional privileges;

- `sftponly` - SFTPonly accounts are forbidden to be in any other group, but since they need SSH access, this group allows it;

If you add your account to `sshusers`, you should be fine. If it's an admin account, adding it to `admins` instead will also suffice.

**Comment by xbeta** [comment]
@drybjed sorry I miss that age on the doc, but it has the same attributes.
I do end up using Group, but it would be nice if we can choose our own group names, because that's what we need in my case

**Comment by drybjed** [comment]
@xbeta Right. `debops.sshd` needs to be overhauled at some point, I'll probably do it when I will work on SSH public key support and authorization on LDAP. Right now you can set the list of groups using:
```
sshd_AllowGroups: 'root admins sshusers sftponly'
```

**Comment by ypid** [comment]
Variable has been renamed in #19. Example would now be:

```YAML
sshd_allow_groups: 'root admins sshusers sftponly'
```

**Comment by drybjed** [comment]
Additionally, if `sshd_allow_groups` is set to `[]`, it's removed from the config and this particular restriction is disabled.
