### ISSUE TITLE
Paranoia mode

### ISSUE THREAD

**Issue by ypid** [debops/ansible-sshd#20]
With the latest changes (#19) it would be pretty easy (if configured) to only allow the first cypher, mac in the list (which is ordered after preference) and drop support for all others entirely what do you think about such an option like `sshd_paranoid` to do this?

Of course this only makes sense if you don’t have a big user base or security aware user base so that they can still login.

**Comment by drybjed** [comment]
With current set of ciphers you cannot connect to `sftponly` account using Midnight Commander - looks like `mc` does not support newer options. So that's at least one use case that's broken right now. I'm afraid to think what will happen when we drop more. :-)

I suppose it could be added after some testing and if there's more interest, but current defaults are probably fine in most cases (caveat: IANASE).

**Comment by ypid** [comment]
`sshd_paranoid` would be False be default of course and should only be enabled if your are ok with things breaking. The defaults in #19 also look good to me and (https://github.com/BetterCrypto/Applied-Crypto-Hardening/tree/master/src/configuration/SSH/OpenSSH) says about the same but also IANASE.
Would you merge a `sshd_paranoid` patch?

**Comment by drybjed** [comment]
Sure, since I'm going to need to make `v0.2.1` right away anyway, why not. Show me what you got. :-)
