### ISSUE TITLE
appears to have window where sshd is enabled with less secure configuration

### ISSUE THREAD

**Issue by sourcejedi** [debops/ansible-sshd#49]
Reading ansible-sshd, the "sensible" defaults disable password authentication, for example.  But this configuration is not imposed until _after_ sshd is installed.

See [http://unix.stackexchange.com/questions/321621/configuring-my-sshd-securely-with-automation](http://unix.stackexchange.com/questions/321621/configuring-my-sshd-securely-with-automation). If the system crashed or lost power between the two steps, it could start later with the insecure configuration, and could run like that for some time.

dpkg-divert can be used, for an example using ansible see https://github.com/debops-contrib/ansible-etckeeper/blob/master/tasks/main.yml

**Comment by drybjed** [comment]
I suppose that this should be explored further, here are my thoughts.

First of all, is this host managed remotely? Then I imagine that you are using SSH to manage it (not sure, might be Kerberos + `remctl`, an option for the future perhaps?), so the `sshd` daemon is already running. Therefore generating a proper configuration can really happen at any point in the role. What you should be doing instead, is ensuring that your deployment method (VM image, Debian Preseed postinst script, `cloud-init`, etc.) has properly secured SSH access and preferably added your public keys to the host so that you can login with `PasswordAuthentication no` already in place.

An option to use `dpkg-divert` to preserve the original `sshd_config` would be great, if the `openssh-server` package used this mechanism. [But it doesn't](https://sources.debian.net/src/openssh/1:6.7p1-5%2Bdeb8u3/debian/openssh-server.postinst/). Configuration file is either `cat`ed from scratch, or modified via Perl. Therefore in my opinion there's nothing to preserve. And, `dpkg-divert` wouldn't do a thing for package upgrades, since the diversions are ignored.

I suppose that the configuration template task could be moved before the APT package install task, for those rare cases where the OpenSSH server is installed for the first time by this role - I guess that could happen if you use it as standalone. We just need to check if templating works without any edge cases like installed package version, list of existing host keys, etc. I suppose that it might be worth a look.

**Comment by sourcejedi** [comment]
Thanks for your detailed thoughts! More than I deserve, for an attempted solution which wasn't properly tested. Looking at your link also taught me about `/etc/sshd_not_to_be_run` (which the systemd service respects as well).

FWIW, on the computers I'm playing around with, my idea is that I run ansible from a local console, at least initially.  I read you can also use ansible from inside vagrant, maybe that would have the same issue.  (If you _want_ to say that `sshd` must already be running, before this ansible role would have started it, then I'm sure you could write that into the role as an assertion :).

**Comment by drybjed** [comment]
Assertion isn't needed - at this point role enters with ssh in "unknown" state and leaves with configured. I suppose that there could be a task that adds `/etc/sshd_not_to_be_run` before package installation, another task that removes it afterwards. Then the role should make sure that it ends with `sshd` running. Although if for some reason the `openssh-server` package is upgraded while the role is executed remotely, you can lose access to the host. So, perhaps a boolean option instead, to enable/disable this functionality as needed.

**Comment by sourcejedi** [comment]
> if for some reason the openssh-server package is upgraded while the role is executed

like cron-apt :(. Thanks again for your thoughts.

So I was wrong to say the condition "sshd is already running".[*] I think the condition should be "openssh-server is already installed".  If it's already installed, then effectively running `apt-get install openssh-server` should never start sshd.  Even if the package is being upgraded, there won't be a window where the package is not installed.

I think it should be an assertion _if_ you decided debops doesn't want to support systems which don't already have sshd enabled, and it was too much effort to make sure the debops role behaved safely in this case.

Notice that if one had asserted the bad condition "sshd must already be running", it would not have risked losing access.  It might be annoying (causing the play to fail).  However the play could still be retried (and ansible has specific support around retries).  I'd guess the play would fail anyway if it tried to `apt-get install` a package at the same time an upgrade was running.

---

[*] "Is enabled" is what I really wanted, but I didn't know a command to test that for sysvinit.  Perhaps  one could use `service name=ssh state=enabled` with `check_mode: yes` (ansible 2.2 feature).

**Comment by drybjed** [comment]
I don't think that denying support for hosts that don't have SSH running is needed. As I said before, I think that moving task which generates the `/etc/ssh/sshd_config` file before the APT task could probably work, we just need to check if it generates the file correctly and add all missing pieces like creation of `/etc/ssh` if needed. Since you are working with systems that don't have SSH by default, go ahead and try it, see what are the results.

**Comment by sourcejedi** [comment]
Tested in systemd-nspawn, debian jessie, ansible-sshd installed from ansible-galaxy.  Moving the config file creation to the start (before the package install) generates an error

    fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "msg": "AnsibleUndefinedVariable: 'sshd__register_host_keys' is undefined"}

it might be possible to just drop the explicit host key configuration.  However there's a version test e.g. determining support for `AuthorizedKeysCommand`...

```
{% if sshd__authorized_keys_lookup|bool and
      sshd__register_version.stdout|d() and
      sshd__register_version.stdout | version_compare('6.2', '>=') %}
AuthorizedKeysCommand /etc/ssh/authorized_keys_lookup
AuthorizedKeysCommandUser {{ sshd__authorized_keys_lookup_user }}
```

I don't wish to change it to test the version in `apt-cache`.  In principle `apt-cache` can show a newer version than the installed package.  I don't wish to work out/assert/document the pre-conditions that let that work correctly.

IMO the solution which involves  testing whether openssh-server is not already installed and using `/etc/sshd/sshd_not_to_be_run` is still a good one :).

**Comment by drybjed** [comment]
Yup, I thought that might happen.

OK, then how about this solution:
- check if `openssh-server` is installed, if so assume that it runs
- if `openssh-server` is not installed, `touch /etc/sshd_not_to_be_run`
- install `openssh-server`
- remove `/etc/sshd_not_to_be_run`
- configure, restart the SSH server as normal
That hopefully will provide a minimal window where the `sshd` daemon might not be started when it actually is supposed to be started (say, `unattended-upgrades` just upgraded the package and did not start the daemon because the file prevented that). There could also be a boolean variable that enables/disables support for this, just in case. It can be enabled by default, to make it easier fot cases like yours.

**Comment by sourcejedi** [comment]
Yep, I am happy with that sequence and default option. I don't think e.g. `unattended-upgrades` can cause a specific problem though. `unattended-upgrades` will not affect whether `openssh-server` is installed, so  `/etc/sshd_not_to_be_run` would not be created. I can't think of a case where you'd want the option... you would have to have other automation that is _installing_ sshd at the same time (and naturally expects it to be running, after a successful install).

(unimportant nitpick: it doesn't assume that sshd is running if openssh-server is installed.  It assumes that sshd is not running if openssh-server is not installed)

**Comment by drybjed** [comment]
OK, sounds good to me. Do you want to try and impement this in the role?

**Comment by sourcejedi** [comment]
Sure :).
