### ISSUE TITLE
Default value of sshd__login_grace_time makes login impossible

### ISSUE THREAD

**Issue by scibi** [debops/ansible-sshd#51]
Hi!

Default value of `sshd__login_grace_time` makes login impossible when DNS servers are unreachable.

I got this issue while deploying new machine in new network. Router wasn't configured yet, so DNS servers were not reachable. I wanted to sshd to this machine from the same L2 network by I couldn't. `sshd` tried to resolve reverse dns of my laptop but it took longer than `20s`. I'm wondering what's the best solution here?
- increase `sshd__login_grace_time`?
- disable reverse DNS resolution?
- set shorter timeouts in `resolv.conf`? (BTW: nice new article about that: https://blog.cloudflare.com/debugging-war-story-the-mystery-of-nxdomain/)

**Comment by drybjed** [comment]
Just to be sure - did the issue go away afrer you had set up the DNS properly?

**Comment by scibi** [comment]
No. DNS are not reachable yet. As a quick hack I increased `LoginGraceTime` manually - it helped. I still had to wait for DNS timeout but I was able to login.

**Comment by drybjed** [comment]
I suppose that changing the grace time to 30 seconds could be a good start to solve this. Since you still have this issue, can you try this value and if it works, make a PR?

**Comment by scibi** [comment]
Sure. I will do this next week.

**Comment by sourcejedi** [comment]
OpenSSH server 6.8 changes the default to "UseDNS no".  https://lwn.net/Articles/637156/

I like the idea that hostnames will appear in logs, but I'm too impatient to accept 20s delays at login time.  Particularly if it's caused by some sort of outage, that I'm trying to resolve or troubleshoot.

There's also a long-overdue change [removing](https://anongit.mindrot.org/openssh.git/commit/?id=e690fe85750e93fca1fb7c7c8587d4130a4f7aba) the "POSSIBLE BREAK-IN ATTEMPT" message (when there is no reverse DNS set up for the client address, and UseDNS is enabled).
