### ISSUE TITLE
allowgroups not working for Ubuntu

### ISSUE THREAD

**Issue by muelli** [debops/ansible-sshd#53]
Ubuntu seems to have no "admins" group, but rather "adm".

It would be nice if debops respected that somehow.

I've just locked myself out of a vagrant box (yk0/ubuntu-xenial), because the "vagrant" user seems to be in these groups: `uid=1000(vagrant) gid=1000(vagrant) groups=1000(vagrant),4(adm),24(cdrom),27(sudo),30(dip),46(plugdev),110(lxd),115(lpadmin),116(sambashare)`.

In general, it would be nice if debops could not lock the user out that is used to have ansible connect to the machine.

**Comment by drybjed** [comment]
According to the [Debian Wiki](https://wiki.debian.org/SystemGroups), the purpose of the `adm` group is:

> Group adm is used for system monitoring tasks. Members of this group can read many log files in /var/log, and can use xconsole. Historically, /var/log was /usr/adm (and later /var/adm), thus the name of the group.

This means that this group has a defined meaning in Debian/Ubuntu, and certain packages/software might be configured to use it. I don't want to change the functionality of the `adm` by allowing members of it access to SSH.

Perhaps a way to solve this would be to add a separate `AllowUsers` entry in the config file, but it looks like this blocks access to the unlisted users.

I think that since you are managing an environment for a Vagrant setup anyway, you should just ensure that a given user account is in the `admins` group. The `debops.users` role should let you do that.

**Comment by muelli** [comment]
The vagrant setup is for testing purposes.  I thought I'd rather lock myself out of a virtual machine than a remote host.

I cannot argue about the specific semantics of any group in Debian or Ubuntu.
Are you saying that it's an Ubuntu bug to not have an "admins" group?  I'll happily raise a bug with them to track it down.

FWIW: The only other user I see in the adm group is "syslog". I understand that giving more users SSH access than necessary is considered to be bad. FTR: the syslog user has /bin/false as their shell.

As far as debops is concerned, being locked out is extremely unfortunate and frustrating, especially if you use the tool in first place to save some work and to follow best practices.  I'm not insisting on any group being added to sshd's AllowGroups. It seems relatively clear to me though, that the current mechanism does not work well (out of the box) with Ubuntu.  I appreciate that the project is called "debops" and not "ubuntuops" so I won't have hard feelings if you just close this issue.

**Comment by drybjed** [comment]
According to [this AskUbuntu answer](http://askubuntu.com/a/122500), current Ubuntu releases use the `sudo` group as the official "administrator group", although that might refer only to the local administrators and not remote users accessing the host over SSH. I don't think that adding `sudo` to the list of groups allowed to connect to the host via SSH is a good idea, it might bring about unintended consequences.

Remember that the DebOps codebase is public, and keeping public code on the conservative side is always a good idea. THe public codebase won't fit everywhere, it just so happens that Vagrant is one of the environments DebOps is not designed for - we are focusing on production environment after all, not development environment. Still, through Ansible inventory you are free (and I'd say pretty much expected) to change the DebOps configuration to fit your needs. In this particular case, you can just modify the list of groups that SSH accepts to include `sudo` if you wish, this will be present in your development (Vagrant) environment, but not in your production environment where that most likely won't be an issue.

**Comment by muelli** [comment]
I don't see why this would not be an issue on an Ubuntu installation on a physical host.  In fact, I would be surprised if debops behaved differently and decide to lock me out in one instance and not the other. As such the conservative decision effectively makes Ubuntu users lose access when they are first trying depobs.

Interestingly enough, in the Ubuntu case the "admin" group does not exist. Yet, OpenSSH is configured to allow access for this group. Some may consider this to not be very conservative and maybe as almost as bad as configuring access for a group that has only one member which has /bin/false as their shell.

To me, the logic for AllowGroups seems to be hard coded to Debian. Maybe checking for Ubuntu and raising a warning or so is an even more conservative approach than blindly configuring AllowGroups..?

**Comment by drybjed** [comment]
DebOps actually creates the `admins` group, either via [the debops.bootstrap role](https://github.com/debops/ansible-bootstrap/blob/master/tasks/admin_accounts.yml#L9-L14), during [preseeding managed by debops.preseed](https://github.com/debops/ansible-preseed/blob/master/templates/srv/www/preseed/configs/d-i/debian.sh.j2#L70), by the [debops.auth role included in common playbook](https://github.com/debops/ansible-auth/blob/master/tasks/main.yml#L13-L19), so when you use the DebOps playbook, optionally prepare the first host with `debops.bootstrap` or create other host via PXE/preseeding managed by DebOps, you should have the `admins` group present on a host, and your admin accounts should belong to it. If, on the other hand you create your own common playbook without the `debops.auth` role, it's your responsibility to make the required system groups, or change the `debops.sshd` configuration to use some other security practices you want.

What I meant by this "not being an issue" was an assumption that you will use the DebOps playbook to deploy the hosts in production, where the `debops.auth` role will ensure that specified groups exist and the admin account is added to them, therefore allowing for SSH access. If that's not the case in your environment, that's my mistake.

I've deploy DebOps on the Ubuntu-based hosts or containers from time to time and I haven't noticed any issues with the `admins` group and SSH access - if they would show up, I would definitely account for them in the playbook.

The groups configured in `AllowGroups` option don't necessarily need to exist in the system - they could be managed via LDAP, for example. Still, DebOps ensures in multiple places that the set of system groups is present - if you don't use the default playbook, you need to ensure that yourself.

The `AllowGroups` option is more flexible than `AllowUsers`, since it lets you manage SSH access on the system level via group presence and not a specific list of usernames in the SSH configuration file. Going with neither is, IMO, not very practical since you allow any user access to the SSH service explicitly.

**Comment by jbicha** [comment]
I was about to file this as a separate bug report, but I'll add it here instead:

I was able to lock myself out of ansible by doing this:

1. Create a fresh Ubuntu 16.04 image (let's call it IMAGE). Add my SSH key and install python.
2. `debops-init FOO`
3. `cd FOO/ansible`
4. Edit `inventory/hosts` to add something like
    IMAGE ansible_ssh_host=128.66.0.100
6. `debops -l IMAGE`

In` /var/log/auth.log` is this error:
`sshd[7210]: User jeremy from 128.66.0.100 not allowed because none of user's groups are listed in AllowGroups`

The default groups on Ubuntu for the first user include 'adm' and 'sudo' but debops has modified` /etc/sshd/ssh_config` to only allow these groups to connect: `root admins sshusers sftponly` Excluding root, none of those groups are present in a default Debian or Ubuntu install.

Perhaps this bug was unnoticed for a while because there's an implicit dependency on debops-bootstrap being run first but it's not good to assume that.

Suggested fix
-----------------
At least ensure the current ansible user is in one of the groups allowed to ssh in before restarting ssh with the AllowGroups change.

**Comment by drybjed** [comment]
Point taken. The problem I see here is the source of truth that specifies which user accounts should be included in the `admins` system group which grans system administrator access. The current implementation seems incomplete:

- the user accounts included in the `admins` group are defined by the deployment process - think `cloud-init`, PXE/preseed or manual bootstrapping via `debops.bootstrap` role
- the `debops.core` role [defines Ansible facts](https://github.com/debops/ansible-core/blob/master/templates/etc/ansible/facts.d/core.fact.j2#L76-L81) which specify what system accounts are administrator accounts. This is based on the [list of groups to check](https://github.com/debops/ansible-core/blob/master/defaults/main.yml#L111-L115) if no administrator accounts are set explicitly
- BUT there is no enforcement of the group membership in the main playbook, per se. This is due to the fact that this was previously done by the `debops.users` role which used separate list of admin accounts. This was removed at some point when the role was redesigned.

The [solution](https://github.com/debops/ansible-sshd/pull/55/files) proposed by @jbicha sounds like the correct idea but in a wrong place. I think that the `debops.auth` role itself should ensure the user accounts specified by the `debops.core` Ansible facts are included in the `admins` system group. That way there's one specific place to set the configuration for Vagrant - in Vagrant inventories, define the list of `core__admin_groups` as both `admins` and `sudo`; this then should correctly propagate to the roles that use the `debops.core` facts to manage admin accounts. I'll try to implement that shortly.

**Comment by drybjed** [comment]
NB, the `debops.auth` role will be split in the future into smaller roles that manage different authentication and authorization options, so the admin account management will probly be moved elsewhere at some point, but it can be included there for now.

**Comment by drybjed** [comment]
The needed changes [have been implemented in debops.auth](https://github.com/debops/ansible-auth/pull/33). @muelli, @jbicha, can you check if this solves the issues you mentioned. Remember that with Vagrant you can add the `sudo` group to `core__admin_groups` list in the Ansible inventory, which should ensure that the `vagrant` user will be added to the `admins` group.

**Comment by jbicha** [comment]
@drybjed Your fix did not work for me because the current ansible_user is not automatically considered a debops admin account.

Running the basic debops command should never automatically lock the current user out of ssh, if for no other reason than debops requires ssh to work! :)

**Comment by drybjed** [comment]
Hmm. I guess `debops.auth` could default to `'{{ ansible_user | d(ansible_ssh_user) }}'` in that case; not sure if this will be picked up by Ansible, need to check.

@jbicha What happens if you specify `core__admin_users` in the Ansible inventory with your username?

**Comment by jbicha** [comment]
@drybjed Yes, setting this worked:

`core__admin_users: [' "{{ ansible_user_id }}" ']`

**Comment by drybjed** [comment]
@jbicha Good to know. Now, do you plan to implement some kind of deployment scheme, or are you just installing default images all the time? Do you use `cloud-init` or preseeding of some kind, or custom images?

**Comment by jbicha** [comment]
I have a small webserver I use for a few different websites and services. I want to deploy Ubuntu to a VPS on something like EC2 or DigitalOcean (DO).

I've been using cloud-init to bootstrap since debops.bootstrap didn't [work](https://github.com/debops/ansible-bootstrap/issues/43) for me. I've been using lxd lately for testing although DO is probably cheap enough too.

I'm a beginner with debops and ansible and still feel I have a lot more to learn to use them effectively

**Comment by drybjed** [comment]
Great. In that case in your `cloud-init` config just add the `admins` group and include your admin account in it. This should make DebOps work out of the box for you.

**Comment by drybjed** [comment]
I have changed the `debops.core` role to use the `ansible_user` or `ansible_ssh_user` or `$USER` from the Ansible Controller by default. The fact script also merges the two data sources (list of admin accounts and UNIX accounts belonging to specified groups). Can you check if that solves the issue on normal installations without bootstrap/preseeding as well as in Vagrant?

**Comment by jbicha** [comment]
This works for me now with the latest debops.auth and debops.core. Thanks!

**Comment by drybjed** [comment]
This issue seems to be resolved so I'll close it now.
